using Microsoft.EntityFrameworkCore;
using Npgsql;
using TodoList.Access;

namespace TodoList.Host.Infrastructure;

public static class DatabaseInitializationExtensions
{
    public static async Task InitializeDatabaseAsync(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<TodoDbContext>();
        var logger = scope.ServiceProvider
            .GetRequiredService<ILoggerFactory>()
            .CreateLogger("DatabaseInitialization");

        const int maxAttempts = 8;

        for (var attempt = 1; attempt <= maxAttempts; attempt++)
        {
            try
            {
                await EnsureSchemaAsync(dbContext, cancellationToken: default);
                return;
            }
            catch (Exception ex) when (IsTransient(ex) && attempt < maxAttempts)
            {
                logger.LogWarning(
                    ex,
                    "Database initialization attempt {Attempt} of {MaxAttempts} failed. Retrying in 2 seconds.",
                    attempt,
                    maxAttempts);

                await Task.Delay(TimeSpan.FromSeconds(2));
            }
        }

        await EnsureSchemaAsync(dbContext, cancellationToken: default);
    }

    private static async Task EnsureSchemaAsync(TodoDbContext dbContext, CancellationToken cancellationToken)
    {
        await dbContext.Database.EnsureCreatedAsync(cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS users (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name character varying(150) NOT NULL,
                email character varying(320) NOT NULL,
                normalized_email character varying(320) NOT NULL,
                password_hash text NOT NULL,
                created_at_utc timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ix_users_normalized_email
            ON users (normalized_email);
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE users
            ADD COLUMN IF NOT EXISTS full_name character varying(150);
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE users
            ADD COLUMN IF NOT EXISTS email character varying(320);
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE users
            ADD COLUMN IF NOT EXISTS normalized_email character varying(320);
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE users
            ADD COLUMN IF NOT EXISTS password_hash text;
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE users
            ADD COLUMN IF NOT EXISTS created_at_utc timestamp with time zone;
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE tasks
            ADD COLUMN IF NOT EXISTS user_id integer;
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS ix_tasks_user_id_id
            ON tasks (user_id, id);
            """,
            cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'fk_tasks_users_user_id'
                ) THEN
                    ALTER TABLE tasks
                    ADD CONSTRAINT fk_tasks_users_user_id
                    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            cancellationToken);
    }

    private static bool IsTransient(Exception exception) =>
        exception is TimeoutException
        || exception is NpgsqlException
        || exception is InvalidOperationException
        || exception is DbUpdateException;
}
